#!/usr/bin/perl
#Contributors: Matt Larson
#Last updated: 08/17/2019

#computes the topological local zeta function associated to a Newton polyhedron

use strict;
use warnings;
use application "polytope";
use PDL;
use Algorithm::Combinatorics "subsets";



#usage: multiplicityArray(AoA)
#computes the multiplicity of a pair of integer vectors
#i.e. computes the index of the lattice generated by the vectors in the group of all lattice points 
#in the vector space spanned by the vectors
#does this by taking the gcd of the determinents of the 2x2 minors
sub multiplicityArray{
	my @vectors = @{shift @_};
	my $num = scalar(@vectors);
#	my @pairs = subsets([0..scalar(@v1)-1], 2);
#	my $gcd = new Integer abs($v1[0]*$v2[1] - $v2[0]*$v1[1]);
#	for my $sub(@pairs){
#		my $det = abs($v1[$sub->[0]]*$v2[$sub->[1]] - $v2[$sub->[0]]*$v1[$sub->[1]]);
#		my $toint = new Integer($det);
#		$gcd = gcd($gcd, $toint);
#		if ($gcd == 1){
#			last;
#		}
#	}
	return $gcd;
}


#usage:facetContribution(diagram, array of vertices)
#the array of vertices should form a facet

sub facetContribution{

}








